
export default () => ({
  isLoadin: true,
  products: [
    {
      id: "1",
      name: "Laptop",
      img: "product01.png",
      price: "17890",
      discount: "30",
      rating: "5",
      typeProduct: "NEW",
    },
    {
      id: "2",
      name: "Audífonos",
      img: "product02.png",
      price: "590",
      discount: "30",
      rating: "3",
      typeProduct: "NEW",
    },
    {
      id: "3",
      name: "Laptop",
      img: "product03.png",
      price: "23490",
      discount: "30",
      rating: "4",
      typeProduct: "NEW",
    },
    {
      id: "4",
      name: "Tablet",
      img: "product04.png",
      price: "6990",
      discount: "30",
      rating: "5",
      typeProduct: "NEW",
    },
    {
      id: "5",
      name: "Audífonos",
      img: "product05.png",
      price: "990",
      discount: "30",
      rating: "4",
      typeProduct: "NEW",
    },
    {
      id: "6",
      name: "Laptop",
      img: "product01.png",
      price: "17890",
      discount: "30",
      rating: "5",
      typeProduct: "NEW",
    },
    {
      id: "7",
      name: "Audífonos",
      img: "product02.png",
      price: "590",
      discount: "30",
      rating: "3",
      typeProduct: "NEW",
    },
    {
      id: "8",
      name: "Laptop",
      img: "product03.png",
      price: "23490",
      discount: "30",
      rating: "4",
      typeProduct: "NEW",
    },
    {
      id: "9",
      name: "Tablet",
      img: "product04.png",
      price: "6990",
      discount: "30",
      rating: "5",
      typeProduct: "NEW",
    },
    {
      id: "10",
      name: "Audífonos",
      img: "product05.png",
      price: "990",
      discount: "30",
      rating: "4",
      typeProduct: "NEW",
    },
    {
      id: "11",
      name: "Laptop",
      img: "product01.png",
      price: "17890",
      discount: "30",
      rating: "5",
      typeProduct: "NEW",
    },
    {
      id: "12",
      name: "Audífonos",
      img: "product02.png",
      price: "590",
      discount: "30",
      rating: "3",
      typeProduct: "NEW",
    },
    {
      id: "13",
      name: "Laptop",
      img: "product03.png",
      price: "23490",
      discount: "30",
      rating: "4",
      typeProduct: "NEW",
    },
    {
      id: "14",
      name: "Tablet",
      img: "product04.png",
      price: "6990",
      discount: "30",
      rating: "5",
      typeProduct: "NEW",
    },
    {
      id: "15",
      name: "Audífonos",
      img: "product05.png",
      price: "990",
      discount: "30",
      rating: "4",
      typeProduct: "NEW",
    },
    {
      id: "16",
      name: "Laptop",
      img: "product01.png",
      price: "17890",
      discount: "30",
      rating: "5",
      typeProduct: "NEW",
    },
    {
      id: "17",
      name: "Audífonos",
      img: "product02.png",
      price: "590",
      discount: "30",
      rating: "3",
      typeProduct: "NEW",
    },
    {
      id: "18",
      name: "Laptop",
      img: "product03.png",
      price: "23490",
      discount: "30",
      rating: "4",
      typeProduct: "NEW",
    },
    {
      id: "19",
      name: "Tablet",
      img: "product04.png",
      price: "6990",
      discount: "30",
      rating: "5",
      typeProduct: "NEW",
    },
    {
      id: "20",
      name: "Audífonos",
      img: "product05.png",
      price: "990",
      discount: "30",
      rating: "4",
      typeProduct: "NEW",
    },
  ],
  hotdealDate: new Date(),
  productsCollection: [
    {
      id: "1",
      img: "shop01.png",
    },
    {
      id: "2",
      img: "shop02.png",
    },
    {
      id: "3",
      img: "shop03.png",
    },
  ],
})